apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "api.fullname" . }}
  labels:
    app: {{ template "api.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "api.name" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "api.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.image.secretName }}
      terminationGracePeriodSeconds: 120
      containers:
      - name: {{ template "api.fullname" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
          - containerPort: {{ .Values.service.http }}
            name: http
        args:
{{ toYaml .Values.image.arguments | indent 10 }}
        env:
          {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value | quote}}
        {{- end }}
        readinessProbe:
          httpGet:
            path: /en
            port: {{ .Values.service.http }}
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
