apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: FREEJE_SESSION
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.host }}
  name: {{ template "api.fullname" . }}
  labels:
    app: {{ template "api.name" . }}
    chart: {{ template "api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.service.http }}
      name: http
      protocol: TCP
      targetPort: http
  selector:
    app: {{ template "api.name" . }}
    release: {{ .Release.Name }}
