#env:
  - name: REDREPORT_TOKEN
    value: 4401|FN7ga3IOtcE0rMOoQlU6OwJ6kEpHDG7GCh0E1Z3j6752e4b5
  - name: NEXTAUTH_SECRET
    value: yvvmm3JA9ZR5DNPy4UwIcxqtVacKLPuUiiIhQT/z7BI=
  - name: GOOGLE_CLIENT_SECRET
    value: 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
  - name: KEYCLOAK_CLIENT_SECRET
    value: pemnHGN7ExIzInxB6xMwHtGivT9WSc8A
  - name: KEYCLOAK_ADMIN_SECRET
    value: NjvFIbvyOXvv7aj5zrLEiom77abiYHdP
