# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: registry.gitlab.com/betacompany/freeje/nextacc
  tag: prod
  pullPolicy: IfNotPresent
  secretName: gitlab-nextacc
  secretCr: ICB7CiAgICAiYXV0aHMiOiB7CiAgICAgICJyZWdpc3RyeS5naXRsYWIuY29tIjogewogICAgICAgICJhdXRoIjogIloybDBiR0ZpSzJSbGNHeHZlUzEwYjJ0bGJpMDFNemd3TkRNek9tZHNaSFF0UVZSNFdITjZXa2N0WTNoNVNuRmxUbVZ3WVZBPSIKICAgICAgfQogICAgfQogIH0K

ingress:
  host: nextacc.telecomax.net

service:
  http: 3000

#resources:
#  limits:
#   cpu: 0.5
#   memory: 128Mi
#  requests:
#   cpu: 0.5
#   memory: 128Mi

nodeSelector: [ ]

tolerations: [ ]

affinity: { }

env:
  - name: SITE_ID
    value: 23
  - name: REDREPORT_URL
    value: https://redreport.freeje.org
  - name: NEXTAUTH_URL
    value: https://nextacc.telecomax.net
  - name: GOOGLE_CLIENT_ID
    value: 991863475034-o8k6b7sbp7ttc6769pfealsi6t76r71g.apps.googleusercontent.com
  - name: KEYCLOAK_CLIENT_ID
    value: target-client
  - name: KEYCLOAK_REALM
    value: https://keycloak.telecomax.net/auth/realms/blabla
  - name: KEYCLOAK_REALM_NAME
    value: blabla
  - name: KEYCLOAK_ADMIN_ID
    value: admin-cli
  - name: KEYCLOAK_ADMIN_REALM
    value: https://keycloak.telecomax.net/auth/admin/realms/blabla
  - name: SLACK_WEBHOOK
    value: https://hooks.slack.com/services/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
  - name: NEXT_PUBLIC_D1_WORKER_URL
    value: https://d1-storage.eri-42e.workers.dev
